## Numpy Tutorial - 1

In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3,4,5,6])
print(a)
print(a[1])
print(a[1:])
print(a[:-2])

a[2] = 10
print(a)

[1 2 3 4 5 6]
2
[2 3 4 5 6]
[1 2 3 4]
[ 1  2 10  4  5  6]


## Multiidimensional numpy arrays

In [5]:
a_mul = np.array([[1,2,3,4],
                [4,5,6,9],
                [7,8,9,11]])
print(a_mul[0])
print(a_mul[0,1])

[1 2 3 4]
2


In [9]:
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

(3, 4)
2
12
int64


In [16]:
a = np.array([
                [1,2,3],
                [4, "5", 8],
                [7,8,9]
            ], dtype = np.int32)
print(a.dtype)
print(a[0,0])
print(type(a[0][0]))

int32
1
<class 'numpy.int32'>


In [17]:
a = np.array([
                [1,2,3],
                [4, "5", 8],
                [7,8,9]
            ], dtype = np.float64)
print(a.dtype)
print(a[0,0])
print(type(a[0][0]))

float64
1.0
<class 'numpy.float64'>


In [20]:
d = {'1': 'A'}
a = np.array([
                [1,2,3],
                [4, d, 8],
                [7,8,"Hello"]
            ])
print(a.dtype)
print(a[0,0])
print(type(a[0][0]))      # unoptimized python integer instead of optimised `int32`

object
1
<class 'int'>


In [30]:
a = np.full((2,3,4), 9)
print(a)

a0 = np.zeros((10,5,2))
print(a0)

a1 = np.ones((10,5,2))
print(a1)

a_empty = np.empty((3,3,3))         # allocates the space without filing in the values
print(a_empty)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]


### Filing arrays

In [31]:
x_values = np.arange(0,1000,5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [35]:
x_values = np.linspace(0,1000, 1001)
print(x_values)

[   0.    1.    2. ...  998.  999. 1000.]


In [36]:
print(np.nan)
print(np.inf)

nan
inf


In [37]:
print(np.isnan(np.nan))
print(np.isinf(np.inf))

True
True


In [39]:
print(np.isnan(np.sqrt(-1)))
print(np.isinf(np.array([10])/0))

True
[ True]


/var/folders/jm/ghwgvclx7g3d68lp4w8vhpp40000gn/T/ipykernel_84583/3338874168.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
/var/folders/jm/ghwgvclx7g3d68lp4w8vhpp40000gn/T/ipykernel_84583/3338874168.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10])/0))


### Mathematical Operations

In [40]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 5)
print(a1 * 5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]


In [44]:
print(l1 + l2)
print(a1 + 5)
print(a1 + a2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[ 6  7  8  9 10]
[ 7  9 11 13  5]


In [45]:
print(a1 - a2)
print(a1 / a2)

[-5 -5 -5 -5  5]
[0.16666667 0.28571429 0.375      0.44444444        inf]


/var/folders/jm/ghwgvclx7g3d68lp4w8vhpp40000gn/T/ipykernel_84583/869607138.py:2: RuntimeWarning: divide by zero encountered in divide
  print(a1 / a2)


In [46]:
a1 = np.array([1,2,3])
a2 = np.array([[1],
                [2]])

print(a1 * a2)

[[1 2 3]
 [2 4 6]]


In [47]:
a = np.array([[1,2,3],
                [4,5,6]])
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.log10(a))
print(np.exp2(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
[[ 2.  4.  8.]
 [16. 32. 64.]]


### Array Methods

In [49]:
a = np.array([1,2,3])
print(np.append(a, [7,8,9]))
print(a)

a = np.append(a, [7,8,9])
print(a)
a = np.insert(a,3, [4,5,6,7])
print(a)

[1 2 3 7 8 9]
[1 2 3]
[1 2 3 7 8 9]
[1 2 3 4 5 6 7 7 8 9]


In [53]:
a = np.array([[1,2,3,4,56],
            [4,8,1,2,3],
            [9,7,5,4,2]])

print(np.delete(a,1,0))

print(np.delete(a,3,1))


[[ 1  2  3  4 56]
 [ 9  7  5  4  2]]
[[ 1  2  3 56]
 [ 4  8  1  3]
 [ 9  7  5  2]]


### Structuring Methods


In [60]:
a = np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20]])

print(a.shape)
print(a.reshape((5,4)))
print(a.reshape(20,))
print(a.reshape(20,1)) 
print(a.reshape(2,2,5)) 
print(a.reshape(1,1,1,1,2,10))

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
[[[[[[ 1  2  3  4  5  6  7  8  9 10]
     [11 12 13 14 15 16 17 18 19 20]]]]]]


In [67]:
a.reshape((10,2))
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [68]:
a.resize((10,2))
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [69]:
print(a.flatten())   # returns a flatten copy of the array
print(a.ravel())     # returns a flatten view of the array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [71]:
var1 = a.flatten()
var1[2] = 100
print(var1)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [72]:
var1 = a.ravel()        
var1[2] = 100       # it will actually change the original array
print(var1)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2]
 [100   4]
 [  5   6]
 [  7   8]
 [  9  10]
 [ 11  12]
 [ 13  14]
 [ 15  16]
 [ 17  18]
 [ 19  20]]


In [73]:
a = np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,12,13,14,15],
            [16,17,18,19,20]])

var  = [v for v in a.flat]
print(var)

[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]


In [75]:
# transposing or swapping of axis
print(a.transpose())
print(a.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [76]:
print(a.swapaxes(0,1))

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


### Concatenating, Stacking and Splitting

In [ ]:
a1 = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

a2 = np.array([[11,12,13,14,15],
                [16,17,18,19,20]])

print(np.concatenate((a1,a2), axis = 1))
print(np.concatenate((a1,a2), axis = 0))



[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [84]:
print(a1)
print(a2)
a = np.stack((a1,a2))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [87]:
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [94]:
a = np.array([[1,2,3,4,5,6],
            [6,7,8,9,10,11],
            [11,12,13,14,15,16],
            [16,17,18,19,20,21]])

print(np.split(a, 6, axis = 1))

[array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]]), array([[ 5],
       [10],
       [15],
       [20]]), array([[ 6],
       [11],
       [16],
       [21]])]


### Aggregate Functions

In [95]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

1
21
11.0
5.84522597225006
264
11.0


### Numpy Random

In [ ]:
numbers = np.random.randint(10, 20, size=(2,3,4))
print(numbers)

[[[16 19 18 16]
  [16 11 11 16]
  [19 12 18 13]]

 [[18 15 15 14]
  [16 12 10 13]
  [11 19 17 16]]]


In [100]:
numbers = np.random.binomial(10, p=0.5, size=(5,10))
print(numbers)

[[5 5 3 4 4 5 7 6 5 6]
 [5 4 7 5 3 6 5 7 4 4]
 [4 6 6 6 3 5 5 4 2 7]
 [6 5 6 3 7 3 7 4 5 3]
 [6 4 2 5 4 5 7 5 2 1]]


In [101]:
numbers = np.random.normal(loc = 170, scale = 15, size=(5,10))
print(numbers)

[[187.39083086 170.49097943 170.24464979 181.17711148 171.37527357
  177.74032302 171.47469858 166.77286584 176.71482063 176.47416162]
 [167.17024115 188.33012274 180.12911533 176.77955052 194.52759231
  227.54498312 172.53471033 153.0889859  165.25337512 164.33885371]
 [196.11759974 174.9959284  147.4970018  164.58162211 158.80390631
  177.99161098 191.09129207 177.66069874 192.09576292 175.745785  ]
 [188.1249904  144.84642739 159.28646393 183.64443159 162.83768268
  142.5008232  197.15025717 166.70746742 167.24867531 172.97721361]
 [192.29723445 169.41532697 181.94743654 175.19343965 151.72631918
  171.1534996  164.76602005 165.10080466 169.78151819 158.43520092]]


In [102]:
numbers = np.random.choice([10,20,30,40,50], size=(5,10))
print(numbers)

[[20 40 50 20 10 30 50 30 50 10]
 [40 40 10 30 20 30 20 30 20 20]
 [10 10 40 20 20 50 20 40 20 20]
 [40 40 40 10 30 20 50 50 20 10]
 [30 10 10 10 20 40 20 10 10 20]]


### Exporting and Importing Numpy Arrays

In [103]:
a = np.array([[1,2,3,4,5,6],
            [6,7,8,9,10,11],
            [11,12,13,14,15,16],
            [16,17,18,19,20,21]])
np.save("myarray.npy", a)

In [104]:
b = np.load("myarray.npy")
print(b)

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]
 [11 12 13 14 15 16]
 [16 17 18 19 20 21]]


In [106]:
np.savetxt("myarray.csv", a, delimiter=',')

In [107]:
c = np.loadtxt("myarray.csv", delimiter=",")
print(c)

[[ 1.  2.  3.  4.  5.  6.]
 [ 6.  7.  8.  9. 10. 11.]
 [11. 12. 13. 14. 15. 16.]
 [16. 17. 18. 19. 20. 21.]]
