# Pytorch Tutorials (Initializing Tensors, Math, Indexing, Reshaping)

Resource Link: https://youtu.be/x9JiIFvlUwk

In [3]:
import torch


device  = "mps" if torch.backends.mps.is_available() else "cpu"
print(device)

mps


## Initializing Tensor

In [4]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32,
                            device=device, requires_grad=True)
print(my_tensor)
print(my_tensor.device) 
print(my_tensor.dtype)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='mps:0', requires_grad=True)
mps:0
torch.float32
torch.Size([2, 3])
True


#### Other common initialization methods

In [5]:

x = torch.empty(size=(3,3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.zeros((3,3))
print(x)

x = torch.ones((3,3))
print(x)

x = torch.eye(5,5)
print(x)

x = torch.arange(start=0, end=5, step=1)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.1891, 0.1986, 0.1834],
        [0.4148, 0.3395, 0.8239],
        [0.7263, 0.3320, 0.3558]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])


In [11]:

x = torch.rand((3,3))
print(x)


tensor([[0.0114, 0.6637, 0.1870],
        [0.5644, 0.2894, 0.3596],
        [0.0174, 0.8777, 0.1061]])


In [10]:
x = torch.linspace(start=1, end=4, steps=20)
print(x)

tensor([1.0000, 1.1579, 1.3158, 1.4737, 1.6316, 1.7895, 1.9474, 2.1053, 2.2632,
        2.4211, 2.5789, 2.7368, 2.8947, 3.0526, 3.2105, 3.3684, 3.5263, 3.6842,
        3.8421, 4.0000])


In [8]:
x = torch.empty(size=(4,5)).normal_(mean=1, std=2)
print(x)

tensor([[ 5.5590,  3.4778, -1.5468, -0.5833, -0.0122],
        [ 2.2191,  1.7000,  0.3826, -1.6949, -0.1392],
        [ 0.4259, -0.6228, -3.1469,  0.4551,  2.8391],
        [ 0.5776,  3.4397, -1.6535,  2.4478,  1.4058]])


In [12]:
x = torch.empty(size=(2,7)).uniform_(0,2)
print(x)

tensor([[0.4297, 1.5997, 0.9306, 0.9073, 1.8377, 1.3025, 1.5297],
        [0.1099, 1.1718, 1.3517, 1.2332, 0.1297, 1.5638, 0.2379]])


In [13]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### How to initialize and convert tensors to other types (int, float, double)

In [14]:
tensor = torch.arange(4)
print(tensor.bool())    # convert values to bool
print(tensor.short())   # convert values to int16
print(tensor.long())    # convert values to float16
print(tensor.half())    # float16
print(tensor.float())   # float32
print(tensor.double())  # float64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


#### Array to Tensor conversion and vice versa


In [15]:
import numpy as np

np_array = np.zeros((5,7))
print(np_array)

tensor = torch.from_numpy(np_array)
print(tensor)

np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## Tensor Math and Comparison Operations


In [16]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

#### Addition

In [28]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)
print(z1.dtype)

tensor([10., 10., 10.])
torch.float32


In [29]:
z2 = torch.add(x,y)
print(z2)
print(z2.dtype)

z3 = x + y
print(z3)

tensor([10, 10, 10])
torch.int64
tensor([10, 10, 10])


#### Subtraction

In [22]:
z = x - y
print(z)

tensor([-8, -6, -4])


#### Division

In [23]:
z = torch.true_divide(x,y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


#### Inplace Operations

In [25]:
t = torch.ones(3)
t.add_(x)
t += x
print(t)

tensor([3., 5., 7.])


#### Exponentiation

In [27]:
z = x.pow(2)
print(z)

z = y ** 2
print(z)

tensor([1, 4, 9])
tensor([81, 64, 49])


#### Simple Comparison

In [31]:
z = x > 2   # Assign bool value for every element based on the condition x>2
print(z)

z = y > 2
print(z)

tensor([False, False,  True])
tensor([True, True, True])


#### Matrix Multiplication

In [33]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
print(x1)
print(x2)

x3 = torch.mm(x1, x2)
print(x3)

x4 = x1.mm(x2)
print(x4)

tensor([[0.9376, 0.4865, 0.6130, 0.3852, 0.1719],
        [0.2371, 0.2436, 0.6431, 0.7747, 0.7130]])
tensor([[0.8154, 0.9061, 0.4554],
        [0.6316, 0.7719, 0.7505],
        [0.2472, 0.5785, 0.7996],
        [0.2737, 0.9553, 0.6579],
        [0.4101, 0.2509, 0.3483]])
tensor([[1.3992, 1.9908, 1.5956],
        [1.0105, 1.6939, 1.5631]])
tensor([[1.3992, 1.9908, 1.5956],
        [1.0105, 1.6939, 1.5631]])


#### Matrix Exponentiation

In [35]:
matrix_exp = torch.rand(5,5)
print(matrix_exp)
print(matrix_exp.matrix_power(3))

tensor([[0.6296, 0.0836, 0.4984, 0.2337, 0.6199],
        [0.8780, 0.5094, 0.9808, 0.6666, 0.0380],
        [0.8636, 0.8633, 0.7115, 0.4663, 0.5978],
        [0.2266, 0.7070, 0.4136, 0.8522, 0.4273],
        [0.3992, 0.9917, 0.9958, 0.1120, 0.1039]])
tensor([[3.6676, 3.3755, 4.0637, 2.5290, 2.0589],
        [5.3640, 5.2505, 6.1299, 4.0074, 3.2994],
        [6.3002, 5.8095, 6.8661, 4.5743, 3.8193],
        [4.7707, 4.5142, 5.2414, 3.7606, 2.8329],
        [5.1059, 4.5974, 5.4991, 3.7137, 3.2078]])


#### Element Wise Multiplication

In [36]:
z = x * y
print(z)

tensor([ 9, 16, 21])


#### Dot Product

In [37]:
z = torch.dot(x,y)
print(z)

tensor(46)


#### Batch Matrix Multiplication

In [38]:
batch = 32
n = 10
m = 20
p = 30

In [40]:
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))

out_bmm = torch.bmm(tensor1, tensor2)
print(out_bmm.shape)

torch.Size([32, 10, 30])


#### Example of Broadcasting


In [44]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
print(x1, "\n", x2)

tensor([[0.1937, 0.3169, 0.2803, 0.0397, 0.0651],
        [0.2095, 0.1994, 0.0154, 0.5851, 0.5919],
        [0.0928, 0.3459, 0.4475, 0.7270, 0.2690],
        [0.2630, 0.3534, 0.7283, 0.6981, 0.9140],
        [0.9812, 0.1598, 0.1541, 0.6757, 0.6465]]) 
 tensor([[0.2481, 0.9809, 0.9661, 0.4153, 0.2236]])


In [45]:
z = x1 - x2
print(z)

z = x1 ** x2
print(z)

tensor([[-0.0543, -0.6640, -0.6858, -0.3756, -0.1585],
        [-0.0386, -0.7815, -0.9507,  0.1698,  0.3682],
        [-0.1552, -0.6350, -0.5186,  0.3117,  0.0454],
        [ 0.0149, -0.6275, -0.2378,  0.2828,  0.6903],
        [ 0.7331, -0.8211, -0.8120,  0.2604,  0.4229]])
tensor([[0.6655, 0.3239, 0.2927, 0.2618, 0.5429],
        [0.6786, 0.2057, 0.0177, 0.8004, 0.8893],
        [0.5545, 0.3530, 0.4598, 0.8760, 0.7455],
        [0.7180, 0.3605, 0.7361, 0.8613, 0.9801],
        [0.9953, 0.1655, 0.1642, 0.8498, 0.9071]])


#### Other useful tensor operations

In [63]:
x = torch.tensor([[10,2,3,4], [8,4,0,9]], dtype=torch.float32, requires_grad=True, device=device)

# dim=0 will aggregate each columns
# dim=1 will aggregate each row
sum_x = torch.sum(x, dim=0)
print(sum_x)



values, indices = torch.max(x, dim=0)
print(values,"\n", indices)

tensor([18.,  6.,  3., 13.], device='mps:0', grad_fn=<SumBackward1>)
tensor([10.,  4.,  3.,  9.], device='mps:0', grad_fn=<MaxBackward0>) 
 tensor([0, 1, 0, 1], device='mps:0')


In [64]:
values, indices = torch.min(x, dim=0)
print(values, indices)

tensor([8., 2., 0., 4.], device='mps:0', grad_fn=<MinBackward0>) tensor([1, 0, 1, 0], device='mps:0')


In [65]:
abs_x = torch.abs(x)
print(abs_x)

tensor([[10.,  2.,  3.,  4.],
        [ 8.,  4.,  0.,  9.]], device='mps:0', grad_fn=<AbsBackward0>)


In [66]:
z = torch.argmax(x, dim=0)
print(z)

z = torch.argmin(x, dim=1)
print(z)

tensor([0, 1, 0, 1], device='mps:0')
tensor([1, 2], device='mps:0')


#### Notes:

- The torch.argmax() function in PyTorch returns the indices of the maximum values in an input tensor along a specified dimension or across all dimensions if no dimension is specified.
 If the tensor has multiple maximum values, it returns the index of the first occurrence.
 The function is not differentiable and should be avoided in gradient computations.

- The torch.argmin() function in PyTorch returns the indices of the minimum value(s) of the input tensor, either across the entire flattened tensor or along a specified dimension.
 The output tensor's index type is torch.int64.
 If multiple minimum values exist, it returns the index of the first occurrence

In [67]:
mean_x = torch.mean(x.float(), dim=0)
print(mean_x)

tensor([9.0000, 3.0000, 1.5000, 6.5000], device='mps:0',
       grad_fn=<MeanBackward1>)


In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,2,7])

z = torch.eq(x, y)
print(z)

tensor([False,  True, False])


In [71]:
sorted_y, indices = torch.sort(y, dim=0, descending=True)
print(sorted_y)

tensor([9, 7, 2])


In [76]:
x = torch.tensor([-1, -4, -9,8,9,2, 0, 1,2,3])
z = torch.clamp(x, min=0, max=3)
print(z)

tensor([0, 0, 0, 3, 3, 2, 0, 1, 2, 3])


## Tensor indexing

In [77]:
batch_size = 10
features = 25

x = torch.rand((batch_size, features))
print(x)

tensor([[0.1243, 0.0660, 0.7901, 0.1002, 0.1965, 0.1516, 0.1421, 0.4921, 0.2386,
         0.4628, 0.6634, 0.4460, 0.3008, 0.8950, 0.0045, 0.0176, 0.5159, 0.3147,
         0.2997, 0.6165, 0.4147, 0.2170, 0.3277, 0.8379, 0.8782],
        [0.6910, 0.4720, 0.7952, 0.8548, 0.5355, 0.3611, 0.6796, 0.9178, 0.7917,
         0.8249, 0.3518, 0.7050, 0.4815, 0.2990, 0.0401, 0.4360, 0.3340, 0.6158,
         0.0613, 0.6940, 0.8087, 0.3431, 0.2711, 0.2898, 0.5968],
        [0.3672, 0.7129, 0.2215, 0.7080, 0.3923, 0.8365, 0.3777, 0.9293, 0.3576,
         0.5964, 0.2840, 0.3056, 0.3701, 0.0238, 0.9150, 0.8740, 0.3578, 0.0922,
         0.0151, 0.7362, 0.4426, 0.7140, 0.8680, 0.1713, 0.2636],
        [0.1219, 0.8724, 0.2675, 0.4794, 0.3112, 0.8680, 0.5966, 0.5506, 0.2860,
         0.3466, 0.1427, 0.7190, 0.1712, 0.1301, 0.3256, 0.7429, 0.8280, 0.9127,
         0.8345, 0.7680, 0.7455, 0.8210, 0.8751, 0.5999, 0.0779],
        [0.2243, 0.8711, 0.5900, 0.0876, 0.0397, 0.8122, 0.0654, 0.0482, 0.3301,
       

In [79]:
print(x[0].shape)   # x[0,:]

print(x[:,0].shape)

print(x[2, 0:10])

torch.Size([25])
torch.Size([10])
tensor([0.3672, 0.7129, 0.2215, 0.7080, 0.3923, 0.8365, 0.3777, 0.9293, 0.3576,
        0.5964])


In [80]:
x[0,0] = 100
print(x[:,0])

tensor([100.0000,   0.6910,   0.3672,   0.1219,   0.2243,   0.1622,   0.6336,
          0.3342,   0.4273,   0.5654])


#### Fancy Indexing

In [83]:
x = torch.rand(10)
print(x)
indices = [2,5,8]
print(x[indices])

tensor([0.1875, 0.7059, 0.0728, 0.6963, 0.2824, 0.1664, 0.4486, 0.5893, 0.0330,
        0.0719])
tensor([0.0728, 0.1664, 0.0330])


In [85]:
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x)
print(x[rows, cols])

tensor([[0.3995, 0.4564, 0.2950, 0.4339, 0.0111],
        [0.9270, 0.5656, 0.9693, 0.4397, 0.0954],
        [0.3575, 0.1896, 0.9731, 0.0493, 0.0360]])
tensor([0.0954, 0.3995])


#### More advanced Indexing

In [91]:
x = torch.arange(10)

print(x[(x < 3) | (x > 8)])
print(x[x.remainder(2) == 0])

tensor([0, 1, 2, 9])
tensor([0, 2, 4, 6, 8])


#### Useful Operations

In [92]:
print(torch.where(x > 5, x, x * 2))
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension())
print(x.numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


## Tensor Reshaping

In [93]:
x = torch.arange(9)

x_3x3 = x.view(3,3)
print(x_3x3)
x_3x3 = x.reshape(3,3)
print(x_3x3)


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [94]:
y = x_3x3.t()   
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [99]:
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [101]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2), dim=0))
print(torch.cat((x1,x2), dim=1))

tensor([[0.3818, 0.7842, 0.3129, 0.2184, 0.8712],
        [0.6973, 0.5565, 0.0432, 0.5697, 0.2824],
        [0.2060, 0.5853, 0.8331, 0.7712, 0.9992],
        [0.6096, 0.5804, 0.8670, 0.8601, 0.5550]])
tensor([[0.3818, 0.7842, 0.3129, 0.2184, 0.8712, 0.2060, 0.5853, 0.8331, 0.7712,
         0.9992],
        [0.6973, 0.5565, 0.0432, 0.5697, 0.2824, 0.6096, 0.5804, 0.8670, 0.8601,
         0.5550]])


In [102]:
z = x1.view(-1)
print(z.shape)

torch.Size([10])


In [104]:
batch = 5
x = torch.rand((batch, 2, 5))
print(x)

z = x.view(batch, -1)
print(z)

tensor([[[0.1254, 0.1604, 0.6258, 0.3333, 0.3963],
         [0.9219, 0.4298, 0.0900, 0.9090, 0.2840]],

        [[0.9722, 0.7169, 0.6927, 0.7901, 0.5626],
         [0.4006, 0.2573, 0.1127, 0.3949, 0.0709]],

        [[0.2836, 0.2679, 0.3006, 0.7839, 0.5976],
         [0.6565, 0.8216, 0.1207, 0.5528, 0.6478]],

        [[0.6876, 0.7878, 0.5781, 0.9095, 0.1091],
         [0.9692, 0.6860, 0.5012, 0.4828, 0.7748]],

        [[0.7048, 0.1942, 0.1956, 0.2657, 0.5321],
         [0.3942, 0.8419, 0.5980, 0.2992, 0.7388]]])
tensor([[0.1254, 0.1604, 0.6258, 0.3333, 0.3963, 0.9219, 0.4298, 0.0900, 0.9090,
         0.2840],
        [0.9722, 0.7169, 0.6927, 0.7901, 0.5626, 0.4006, 0.2573, 0.1127, 0.3949,
         0.0709],
        [0.2836, 0.2679, 0.3006, 0.7839, 0.5976, 0.6565, 0.8216, 0.1207, 0.5528,
         0.6478],
        [0.6876, 0.7878, 0.5781, 0.9095, 0.1091, 0.9692, 0.6860, 0.5012, 0.4828,
         0.7748],
        [0.7048, 0.1942, 0.1956, 0.2657, 0.5321, 0.3942, 0.8419, 0.5980, 0.2992,
   

In [107]:
z = x.permute(0,2,1)
print(z)
print(z.shape)

tensor([[[0.1254, 0.9219],
         [0.1604, 0.4298],
         [0.6258, 0.0900],
         [0.3333, 0.9090],
         [0.3963, 0.2840]],

        [[0.9722, 0.4006],
         [0.7169, 0.2573],
         [0.6927, 0.1127],
         [0.7901, 0.3949],
         [0.5626, 0.0709]],

        [[0.2836, 0.6565],
         [0.2679, 0.8216],
         [0.3006, 0.1207],
         [0.7839, 0.5528],
         [0.5976, 0.6478]],

        [[0.6876, 0.9692],
         [0.7878, 0.6860],
         [0.5781, 0.5012],
         [0.9095, 0.4828],
         [0.1091, 0.7748]],

        [[0.7048, 0.3942],
         [0.1942, 0.8419],
         [0.1956, 0.5980],
         [0.2657, 0.2992],
         [0.5321, 0.7388]]])
torch.Size([5, 5, 2])


In [108]:
x = torch.arange(10)
print(x.unsqueeze(0))
print(x.unsqueeze(1))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [109]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)

z = x.squeeze(1)
print(z.shape)

torch.Size([1, 1, 10])
torch.Size([1, 10])
